vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "<C-f>", vim.lsp.buf.format)
vim.keymap.set("n", "<C-h>", vim.lsp.buf.hover)
vim.keymap.set("n", "<C-r>", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>h", "<cmd>ClangdSwitchSourceHeader<cr>")
