vim.keymap.set("n", "<leader>cd", vim.lsp.buf.definition)
vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>ch", vim.lsp.buf.hover)
vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>cs", "<cmd>ClangdSwitchSourceHeader<cr>")
